#!/usr/bin/env bash
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
fi

if [ "$1" = "purge" ]; then
    if id -u netmuxd >/dev/null 2>&1; then
        deluser --system netmuxd || true
    fi

    if getent group netmuxd >/dev/null; then
        delgroup --system netmuxd || true
    fi
fi

exit 0